apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: almanzaCluster
  region: eu-west-1
nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: m3.medium
    desiredCapacity: 10
    volumeSize: 20
    privateNetworking: true