apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: almanza-rabbit
  name: almanza-rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: almanza-rabbit
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: almanza-rabbit
    spec:
      containers:
      - image: rabbitmq
        name: almanza-rabbit
        ports:
        - containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: almanza-rabbit
  name: almanza-rabbit
spec:
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: almanza-rabbit
  type: ClusterIP