--- # Master playbook para servidores web
- hosts: localhost
  gather_facts: no
  collections:
    - community.kubernetes
  vars:
    clusterName: "almanzaCluster"
    region: "eu-west-1"
    kversion: "1.17"
    eksRoleName: eksAlmanzaRole
    subnetIds: ""
    securityGroupIds: ""
    clusterNodegroup: ""
    instanceType: t3.medium
  pre_tasks:
  - name: hora de inicio de ejecucion del playbook
    raw: date > startofrole.log
  roles:
  - eks
  # - { role: redhat_webservers, when: "ansible_os_family == 'RedHat'" }
  # - { role: debian_webservers, when: "ansible_os_family == 'Debian'" }
  post_tasks: 
  - name: hora Fin del role
    raw: date >> startofrole.log